### ISSUE TITLE
How is application startup handled?

### ISSUE THREAD

**Issue by gvoysey** [gvoysey/unlock-plugins#1]
- python script / startup wizard?  (probably)
- YAML ? 
- JSON? (probably not)

**Comment by bgalbraith** [comment]
I think we settled on using a python script that contains a set of values assigned to predefined constants.

Also, in general, I think the flow should be something like this:
1. Read in settings.py (use defaults if it doesn't exist)
2. Instantiate plugin manager and collect plugins
3. Activate DAQ plugins
4. Activate Decoder plugins
5. Instantiate PygletWindow
6. Activate and register App plugins
7. Start event loop
