### ISSUE TITLE
FPS is apparently dependent/blocking on window events / mouseover

### ISSUE THREAD

**Issue by gvoysey** [gvoysey/unlock-plugins#4]

**Comment by bgalbraith** [comment]
In the absence of actually scheduling a function to be called on a timer, this is the default behavior:
https://pyglet.readthedocs.org/en/pyglet-1.2-maintenance/programming_guide/eventloop.html

The reason this is happening in the current hello world app is that it is creating its own pyglet window but doesn't schedule any method to run on the clock.

**Comment by gvoysey** [comment]
okay.  I'm working on this right now, then; i'm going to try to abstract out pyglet functions to the base class and then do as that guide suggests.

**Comment by bgalbraith** [comment]
Right. The architecture really only needs one pyglet window that is shared across all apps. What's there in PygletWindow is more or less what we want, but where that gets instantiated at runtime and then linked with the apps when they get activated by the plugin manager.
